spring:
  datasource:
    url: jdbc:mysql://localhost:3306/archivioutenti
    username: root
    password:  Gaspare1!
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create


